extern Bool bCREnable2D(RDCRecPtr pRDC);
extern Bool bCREnableCMDQ(RDCRecPtr pRDC);
extern Bool bCRInitCMDQInfo(ScrnInfoPtr pScrn, RDCRecPtr pRDC);
extern Bool bEnable2D(RDCRecPtr pRDC);
extern Bool bEnableCMDQ(RDCRecPtr pRDC);
extern Bool bInitCMDQInfo(ScrnInfoPtr pScrn, RDCRecPtr pRDC);
extern Bool bInitHWC(ScrnInfoPtr pScrn, RDCRecPtr pRDC);
extern Bool bRDCRegInit(ScrnInfoPtr pScrn);
extern Bool GetDisaplyStatus(ScrnInfoPtr pScrn);
extern Bool RDCAccelInit(ScreenPtr pScreen);
extern Bool RDCCheckCapture(ScrnInfoPtr pScrn);
extern Bool RDCCloseScreen(int scrnIndex, ScreenPtr pScreen);
extern Bool RDCCursorInit(ScreenPtr pScreen);
extern Bool RDCDriverFunc(ScrnInfoPtr pScrn, xorgDriverFuncOp op, pointer data);
extern Bool RDCFilterModeByBandWidth(ScrnInfoPtr pScrn, DisplayModePtr mode);
extern Bool RDCGetRec(ScrnInfoPtr pScrn);
extern Bool RDCMapMem(ScrnInfoPtr pScrn);
extern Bool RDCMapMMIO(ScrnInfoPtr pScrn);
extern Bool RDCMapVBIOS(ScrnInfoPtr pScrn);
extern Bool RDCModeInit(ScrnInfoPtr pScrn, DisplayModePtr mode);
extern Bool RDCRandRGetInfo(ScrnInfoPtr pScrn, Rotation *rotations);
extern Bool RDCRandRSetConfig(ScrnInfoPtr pScrn, xorgRRConfig *config);
extern Bool RDCSaveScreen(ScreenPtr pScreen, Bool unblack);
extern Bool RDCSetMode(ScrnInfoPtr pScrn, DisplayModePtr mode);
extern Bool RDCUnmapMem(ScrnInfoPtr pScrn);
extern Bool RDCUnmapVBIOS(ScrnInfoPtr pScrn);
extern CBStatus CBIOS_SetEDIDToModeTable(ScrnInfoPtr pScrn, EDID_DETAILED_TIMING *pEDIDDetailedTiming);
extern DisplayModePtr RDCBuildModePool(ScrnInfoPtr pScrn);
extern MODE_INFO VESATable;
extern ULONG GetVRAMInfo(ScrnInfoPtr pScrn);
extern ULONG RDCGetMemBandWidth(ScrnInfoPtr pScrn);
extern void CreateEDIDDetailedTimingList(UCHAR *ucEdidBuffer, ULONG ulEdidBufferSize, EDID_DETAILED_TIMING *pEDIDDetailedTiming);
extern void RDCApertureInit(ScrnInfoPtr pScrn);
extern void RDCDisplayPowerManagementSet(ScrnInfoPtr pScrn, int PowerManagementMode, int flags);
extern void RDCFreeRec(ScrnInfoPtr pScrn);
extern void RDCInitpScrnDual(ScrnInfoPtr pScrn);
extern void RDCPointerMoved(int index, int x, int y);
extern void RDCProbeDDC(ScrnInfoPtr pScrn, int index);
extern void RDCRestore(ScrnInfoPtr pScrn);
extern void RDCSave(ScrnInfoPtr pScrn);
extern void RDCSetHWCaps(RDCRecPtr pRDC);
extern void RDCUnmapMMIO(ScrnInfoPtr pScrn);
extern void RDCVideoInit(ScreenPtr pScreen);
extern void TurnDirectAccessFBON(ScrnInfoPtr pScrn, Bool bTurnOn);
extern void vCRDisable2D(RDCRecPtr pRDC);
extern void vCRWaitEngIdle(RDCRecPtr pRDC);
extern void vDisable2D(RDCRecPtr pRDC);
extern void vFillRDCModeInfo (ScrnInfoPtr pScrn);
extern void vRDCLoadPalette(ScrnInfoPtr pScrn, int numColors, int *indices, LOCO *colors, VisualPtr pVisual);
extern void vRDCOpenKey(ScrnInfoPtr pScrn);
extern void vSetStartAddressCRT1(RDCRecPtr pRDC, ULONG base);
extern void vUpdateHDMIFakeMode(ScrnInfoPtr pScrn);
extern void vWaitEngIdle(RDCRecPtr pRDC);
extern xf86MonPtr RDCDoDDC(ScrnInfoPtr pScrn, int index);
